/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as LearnerImport } from './routes/_learner'
import { Route as AuthImport } from './routes/_auth'
import { Route as LearnerIndexImport } from './routes/_learner/index'
import { Route as XEditorDemoImport } from './routes/x/editor-demo'
import { Route as XDropdownImport } from './routes/x/dropdown'
import { Route as LearnerTasksImport } from './routes/_learner/tasks'
import { Route as LearnerExploreImport } from './routes/_learner/explore'
import { Route as LearnerChatImport } from './routes/_learner/chat'
import { Route as LearnerCalendarImport } from './routes/_learner/calendar'
import { Route as AuthLoginImport } from './routes/_auth.login'
import { Route as LearnerCommunitiesIndexImport } from './routes/_learner/communities/index'
import { Route as LearnerCommunitiesIdRouteImport } from './routes/_learner/communities/$id/route'
import { Route as LearnerCommunitiesCreateIndexImport } from './routes/_learner/communities/create/index'
import { Route as LearnerCommunitiesIdIndexImport } from './routes/_learner/communities/$id/index'
import { Route as LearnerCommunitiesIdThreadsIndexImport } from './routes/_learner/communities/$id/threads.index'
import { Route as LearnerCommunitiesIdCoursesIndexImport } from './routes/_learner/communities/$id/courses.index'
import { Route as LearnerCommunitiesIdArticlesIndexImport } from './routes/_learner/communities/$id/articles.index'
import { Route as LearnerCommunitiesIdThreadsThreadIdImport } from './routes/_learner/communities/$id/threads.$threadId'
import { Route as LearnerCommunitiesCreateIdCourseRouteImport } from './routes/_learner/communities/create/$id/course/route'
import { Route as LearnerCommunitiesCreateIdCommunityRouteImport } from './routes/_learner/communities/create/$id/community/route'
import { Route as LearnerCommunitiesCreateIdCommunityIndexImport } from './routes/_learner/communities/create/$id/community/index'
import { Route as LearnerCommunitiesCreateIdCommunitySettingsImport } from './routes/_learner/communities/create/$id/community/settings'
import { Route as LearnerCommunitiesCreateIdCommunityPublishImport } from './routes/_learner/communities/create/$id/community/publish'
import { Route as LearnerCommunitiesCreateIdCommunityMembersImport } from './routes/_learner/communities/create/$id/community/members'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const LearnerRoute = LearnerImport.update({
  id: '/_learner',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LearnerIndexRoute = LearnerIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnerRoute,
} as any)

const XEditorDemoRoute = XEditorDemoImport.update({
  id: '/x/editor-demo',
  path: '/x/editor-demo',
  getParentRoute: () => rootRoute,
} as any)

const XDropdownRoute = XDropdownImport.update({
  id: '/x/dropdown',
  path: '/x/dropdown',
  getParentRoute: () => rootRoute,
} as any)

const LearnerTasksRoute = LearnerTasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LearnerRoute,
} as any)

const LearnerExploreRoute = LearnerExploreImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LearnerRoute,
} as any)

const LearnerChatRoute = LearnerChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LearnerRoute,
} as any)

const LearnerCalendarRoute = LearnerCalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LearnerRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const LearnerCommunitiesIndexRoute = LearnerCommunitiesIndexImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => LearnerRoute,
} as any)

const LearnerCommunitiesIdRouteRoute = LearnerCommunitiesIdRouteImport.update({
  id: '/communities/$id',
  path: '/communities/$id',
  getParentRoute: () => LearnerRoute,
} as any)

const LearnerCommunitiesCreateIndexRoute =
  LearnerCommunitiesCreateIndexImport.update({
    id: '/communities/create/',
    path: '/communities/create/',
    getParentRoute: () => LearnerRoute,
  } as any)

const LearnerCommunitiesIdIndexRoute = LearnerCommunitiesIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnerCommunitiesIdRouteRoute,
} as any)

const LearnerCommunitiesIdThreadsIndexRoute =
  LearnerCommunitiesIdThreadsIndexImport.update({
    id: '/threads/',
    path: '/threads/',
    getParentRoute: () => LearnerCommunitiesIdRouteRoute,
  } as any)

const LearnerCommunitiesIdCoursesIndexRoute =
  LearnerCommunitiesIdCoursesIndexImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => LearnerCommunitiesIdRouteRoute,
  } as any)

const LearnerCommunitiesIdArticlesIndexRoute =
  LearnerCommunitiesIdArticlesIndexImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => LearnerCommunitiesIdRouteRoute,
  } as any)

const LearnerCommunitiesIdThreadsThreadIdRoute =
  LearnerCommunitiesIdThreadsThreadIdImport.update({
    id: '/threads/$threadId',
    path: '/threads/$threadId',
    getParentRoute: () => LearnerCommunitiesIdRouteRoute,
  } as any)

const LearnerCommunitiesCreateIdCourseRouteRoute =
  LearnerCommunitiesCreateIdCourseRouteImport.update({
    id: '/communities/create/$id/course',
    path: '/communities/create/$id/course',
    getParentRoute: () => LearnerRoute,
  } as any)

const LearnerCommunitiesCreateIdCommunityRouteRoute =
  LearnerCommunitiesCreateIdCommunityRouteImport.update({
    id: '/communities/create/$id/community',
    path: '/communities/create/$id/community',
    getParentRoute: () => LearnerRoute,
  } as any)

const LearnerCommunitiesCreateIdCommunityIndexRoute =
  LearnerCommunitiesCreateIdCommunityIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnerCommunitiesCreateIdCommunityRouteRoute,
  } as any)

const LearnerCommunitiesCreateIdCommunitySettingsRoute =
  LearnerCommunitiesCreateIdCommunitySettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LearnerCommunitiesCreateIdCommunityRouteRoute,
  } as any)

const LearnerCommunitiesCreateIdCommunityPublishRoute =
  LearnerCommunitiesCreateIdCommunityPublishImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => LearnerCommunitiesCreateIdCommunityRouteRoute,
  } as any)

const LearnerCommunitiesCreateIdCommunityMembersRoute =
  LearnerCommunitiesCreateIdCommunityMembersImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LearnerCommunitiesCreateIdCommunityRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_learner': {
      id: '/_learner'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LearnerImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_learner/calendar': {
      id: '/_learner/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof LearnerCalendarImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/chat': {
      id: '/_learner/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LearnerChatImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/explore': {
      id: '/_learner/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof LearnerExploreImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/tasks': {
      id: '/_learner/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LearnerTasksImport
      parentRoute: typeof LearnerImport
    }
    '/x/dropdown': {
      id: '/x/dropdown'
      path: '/x/dropdown'
      fullPath: '/x/dropdown'
      preLoaderRoute: typeof XDropdownImport
      parentRoute: typeof rootRoute
    }
    '/x/editor-demo': {
      id: '/x/editor-demo'
      path: '/x/editor-demo'
      fullPath: '/x/editor-demo'
      preLoaderRoute: typeof XEditorDemoImport
      parentRoute: typeof rootRoute
    }
    '/_learner/': {
      id: '/_learner/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LearnerIndexImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/communities/$id': {
      id: '/_learner/communities/$id'
      path: '/communities/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof LearnerCommunitiesIdRouteImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/communities/': {
      id: '/_learner/communities/'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof LearnerCommunitiesIndexImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/communities/$id/': {
      id: '/_learner/communities/$id/'
      path: '/'
      fullPath: '/communities/$id/'
      preLoaderRoute: typeof LearnerCommunitiesIdIndexImport
      parentRoute: typeof LearnerCommunitiesIdRouteImport
    }
    '/_learner/communities/create/': {
      id: '/_learner/communities/create/'
      path: '/communities/create'
      fullPath: '/communities/create'
      preLoaderRoute: typeof LearnerCommunitiesCreateIndexImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/communities/create/$id/community': {
      id: '/_learner/communities/create/$id/community'
      path: '/communities/create/$id/community'
      fullPath: '/communities/create/$id/community'
      preLoaderRoute: typeof LearnerCommunitiesCreateIdCommunityRouteImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/communities/create/$id/course': {
      id: '/_learner/communities/create/$id/course'
      path: '/communities/create/$id/course'
      fullPath: '/communities/create/$id/course'
      preLoaderRoute: typeof LearnerCommunitiesCreateIdCourseRouteImport
      parentRoute: typeof LearnerImport
    }
    '/_learner/communities/$id/threads/$threadId': {
      id: '/_learner/communities/$id/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/communities/$id/threads/$threadId'
      preLoaderRoute: typeof LearnerCommunitiesIdThreadsThreadIdImport
      parentRoute: typeof LearnerCommunitiesIdRouteImport
    }
    '/_learner/communities/$id/articles/': {
      id: '/_learner/communities/$id/articles/'
      path: '/articles'
      fullPath: '/communities/$id/articles'
      preLoaderRoute: typeof LearnerCommunitiesIdArticlesIndexImport
      parentRoute: typeof LearnerCommunitiesIdRouteImport
    }
    '/_learner/communities/$id/courses/': {
      id: '/_learner/communities/$id/courses/'
      path: '/courses'
      fullPath: '/communities/$id/courses'
      preLoaderRoute: typeof LearnerCommunitiesIdCoursesIndexImport
      parentRoute: typeof LearnerCommunitiesIdRouteImport
    }
    '/_learner/communities/$id/threads/': {
      id: '/_learner/communities/$id/threads/'
      path: '/threads'
      fullPath: '/communities/$id/threads'
      preLoaderRoute: typeof LearnerCommunitiesIdThreadsIndexImport
      parentRoute: typeof LearnerCommunitiesIdRouteImport
    }
    '/_learner/communities/create/$id/community/members': {
      id: '/_learner/communities/create/$id/community/members'
      path: '/members'
      fullPath: '/communities/create/$id/community/members'
      preLoaderRoute: typeof LearnerCommunitiesCreateIdCommunityMembersImport
      parentRoute: typeof LearnerCommunitiesCreateIdCommunityRouteImport
    }
    '/_learner/communities/create/$id/community/publish': {
      id: '/_learner/communities/create/$id/community/publish'
      path: '/publish'
      fullPath: '/communities/create/$id/community/publish'
      preLoaderRoute: typeof LearnerCommunitiesCreateIdCommunityPublishImport
      parentRoute: typeof LearnerCommunitiesCreateIdCommunityRouteImport
    }
    '/_learner/communities/create/$id/community/settings': {
      id: '/_learner/communities/create/$id/community/settings'
      path: '/settings'
      fullPath: '/communities/create/$id/community/settings'
      preLoaderRoute: typeof LearnerCommunitiesCreateIdCommunitySettingsImport
      parentRoute: typeof LearnerCommunitiesCreateIdCommunityRouteImport
    }
    '/_learner/communities/create/$id/community/': {
      id: '/_learner/communities/create/$id/community/'
      path: '/'
      fullPath: '/communities/create/$id/community/'
      preLoaderRoute: typeof LearnerCommunitiesCreateIdCommunityIndexImport
      parentRoute: typeof LearnerCommunitiesCreateIdCommunityRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LearnerCommunitiesIdRouteRouteChildren {
  LearnerCommunitiesIdIndexRoute: typeof LearnerCommunitiesIdIndexRoute
  LearnerCommunitiesIdThreadsThreadIdRoute: typeof LearnerCommunitiesIdThreadsThreadIdRoute
  LearnerCommunitiesIdArticlesIndexRoute: typeof LearnerCommunitiesIdArticlesIndexRoute
  LearnerCommunitiesIdCoursesIndexRoute: typeof LearnerCommunitiesIdCoursesIndexRoute
  LearnerCommunitiesIdThreadsIndexRoute: typeof LearnerCommunitiesIdThreadsIndexRoute
}

const LearnerCommunitiesIdRouteRouteChildren: LearnerCommunitiesIdRouteRouteChildren =
  {
    LearnerCommunitiesIdIndexRoute: LearnerCommunitiesIdIndexRoute,
    LearnerCommunitiesIdThreadsThreadIdRoute:
      LearnerCommunitiesIdThreadsThreadIdRoute,
    LearnerCommunitiesIdArticlesIndexRoute:
      LearnerCommunitiesIdArticlesIndexRoute,
    LearnerCommunitiesIdCoursesIndexRoute:
      LearnerCommunitiesIdCoursesIndexRoute,
    LearnerCommunitiesIdThreadsIndexRoute:
      LearnerCommunitiesIdThreadsIndexRoute,
  }

const LearnerCommunitiesIdRouteRouteWithChildren =
  LearnerCommunitiesIdRouteRoute._addFileChildren(
    LearnerCommunitiesIdRouteRouteChildren,
  )

interface LearnerCommunitiesCreateIdCommunityRouteRouteChildren {
  LearnerCommunitiesCreateIdCommunityMembersRoute: typeof LearnerCommunitiesCreateIdCommunityMembersRoute
  LearnerCommunitiesCreateIdCommunityPublishRoute: typeof LearnerCommunitiesCreateIdCommunityPublishRoute
  LearnerCommunitiesCreateIdCommunitySettingsRoute: typeof LearnerCommunitiesCreateIdCommunitySettingsRoute
  LearnerCommunitiesCreateIdCommunityIndexRoute: typeof LearnerCommunitiesCreateIdCommunityIndexRoute
}

const LearnerCommunitiesCreateIdCommunityRouteRouteChildren: LearnerCommunitiesCreateIdCommunityRouteRouteChildren =
  {
    LearnerCommunitiesCreateIdCommunityMembersRoute:
      LearnerCommunitiesCreateIdCommunityMembersRoute,
    LearnerCommunitiesCreateIdCommunityPublishRoute:
      LearnerCommunitiesCreateIdCommunityPublishRoute,
    LearnerCommunitiesCreateIdCommunitySettingsRoute:
      LearnerCommunitiesCreateIdCommunitySettingsRoute,
    LearnerCommunitiesCreateIdCommunityIndexRoute:
      LearnerCommunitiesCreateIdCommunityIndexRoute,
  }

const LearnerCommunitiesCreateIdCommunityRouteRouteWithChildren =
  LearnerCommunitiesCreateIdCommunityRouteRoute._addFileChildren(
    LearnerCommunitiesCreateIdCommunityRouteRouteChildren,
  )

interface LearnerRouteChildren {
  LearnerCalendarRoute: typeof LearnerCalendarRoute
  LearnerChatRoute: typeof LearnerChatRoute
  LearnerExploreRoute: typeof LearnerExploreRoute
  LearnerTasksRoute: typeof LearnerTasksRoute
  LearnerIndexRoute: typeof LearnerIndexRoute
  LearnerCommunitiesIdRouteRoute: typeof LearnerCommunitiesIdRouteRouteWithChildren
  LearnerCommunitiesIndexRoute: typeof LearnerCommunitiesIndexRoute
  LearnerCommunitiesCreateIndexRoute: typeof LearnerCommunitiesCreateIndexRoute
  LearnerCommunitiesCreateIdCommunityRouteRoute: typeof LearnerCommunitiesCreateIdCommunityRouteRouteWithChildren
  LearnerCommunitiesCreateIdCourseRouteRoute: typeof LearnerCommunitiesCreateIdCourseRouteRoute
}

const LearnerRouteChildren: LearnerRouteChildren = {
  LearnerCalendarRoute: LearnerCalendarRoute,
  LearnerChatRoute: LearnerChatRoute,
  LearnerExploreRoute: LearnerExploreRoute,
  LearnerTasksRoute: LearnerTasksRoute,
  LearnerIndexRoute: LearnerIndexRoute,
  LearnerCommunitiesIdRouteRoute: LearnerCommunitiesIdRouteRouteWithChildren,
  LearnerCommunitiesIndexRoute: LearnerCommunitiesIndexRoute,
  LearnerCommunitiesCreateIndexRoute: LearnerCommunitiesCreateIndexRoute,
  LearnerCommunitiesCreateIdCommunityRouteRoute:
    LearnerCommunitiesCreateIdCommunityRouteRouteWithChildren,
  LearnerCommunitiesCreateIdCourseRouteRoute:
    LearnerCommunitiesCreateIdCourseRouteRoute,
}

const LearnerRouteWithChildren =
  LearnerRoute._addFileChildren(LearnerRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LearnerRouteWithChildren
  '/test': typeof TestRoute
  '/login': typeof AuthLoginRoute
  '/calendar': typeof LearnerCalendarRoute
  '/chat': typeof LearnerChatRoute
  '/explore': typeof LearnerExploreRoute
  '/tasks': typeof LearnerTasksRoute
  '/x/dropdown': typeof XDropdownRoute
  '/x/editor-demo': typeof XEditorDemoRoute
  '/': typeof LearnerIndexRoute
  '/communities/$id': typeof LearnerCommunitiesIdRouteRouteWithChildren
  '/communities': typeof LearnerCommunitiesIndexRoute
  '/communities/$id/': typeof LearnerCommunitiesIdIndexRoute
  '/communities/create': typeof LearnerCommunitiesCreateIndexRoute
  '/communities/create/$id/community': typeof LearnerCommunitiesCreateIdCommunityRouteRouteWithChildren
  '/communities/create/$id/course': typeof LearnerCommunitiesCreateIdCourseRouteRoute
  '/communities/$id/threads/$threadId': typeof LearnerCommunitiesIdThreadsThreadIdRoute
  '/communities/$id/articles': typeof LearnerCommunitiesIdArticlesIndexRoute
  '/communities/$id/courses': typeof LearnerCommunitiesIdCoursesIndexRoute
  '/communities/$id/threads': typeof LearnerCommunitiesIdThreadsIndexRoute
  '/communities/create/$id/community/members': typeof LearnerCommunitiesCreateIdCommunityMembersRoute
  '/communities/create/$id/community/publish': typeof LearnerCommunitiesCreateIdCommunityPublishRoute
  '/communities/create/$id/community/settings': typeof LearnerCommunitiesCreateIdCommunitySettingsRoute
  '/communities/create/$id/community/': typeof LearnerCommunitiesCreateIdCommunityIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/test': typeof TestRoute
  '/login': typeof AuthLoginRoute
  '/calendar': typeof LearnerCalendarRoute
  '/chat': typeof LearnerChatRoute
  '/explore': typeof LearnerExploreRoute
  '/tasks': typeof LearnerTasksRoute
  '/x/dropdown': typeof XDropdownRoute
  '/x/editor-demo': typeof XEditorDemoRoute
  '/': typeof LearnerIndexRoute
  '/communities': typeof LearnerCommunitiesIndexRoute
  '/communities/$id': typeof LearnerCommunitiesIdIndexRoute
  '/communities/create': typeof LearnerCommunitiesCreateIndexRoute
  '/communities/create/$id/course': typeof LearnerCommunitiesCreateIdCourseRouteRoute
  '/communities/$id/threads/$threadId': typeof LearnerCommunitiesIdThreadsThreadIdRoute
  '/communities/$id/articles': typeof LearnerCommunitiesIdArticlesIndexRoute
  '/communities/$id/courses': typeof LearnerCommunitiesIdCoursesIndexRoute
  '/communities/$id/threads': typeof LearnerCommunitiesIdThreadsIndexRoute
  '/communities/create/$id/community/members': typeof LearnerCommunitiesCreateIdCommunityMembersRoute
  '/communities/create/$id/community/publish': typeof LearnerCommunitiesCreateIdCommunityPublishRoute
  '/communities/create/$id/community/settings': typeof LearnerCommunitiesCreateIdCommunitySettingsRoute
  '/communities/create/$id/community': typeof LearnerCommunitiesCreateIdCommunityIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_learner': typeof LearnerRouteWithChildren
  '/test': typeof TestRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_learner/calendar': typeof LearnerCalendarRoute
  '/_learner/chat': typeof LearnerChatRoute
  '/_learner/explore': typeof LearnerExploreRoute
  '/_learner/tasks': typeof LearnerTasksRoute
  '/x/dropdown': typeof XDropdownRoute
  '/x/editor-demo': typeof XEditorDemoRoute
  '/_learner/': typeof LearnerIndexRoute
  '/_learner/communities/$id': typeof LearnerCommunitiesIdRouteRouteWithChildren
  '/_learner/communities/': typeof LearnerCommunitiesIndexRoute
  '/_learner/communities/$id/': typeof LearnerCommunitiesIdIndexRoute
  '/_learner/communities/create/': typeof LearnerCommunitiesCreateIndexRoute
  '/_learner/communities/create/$id/community': typeof LearnerCommunitiesCreateIdCommunityRouteRouteWithChildren
  '/_learner/communities/create/$id/course': typeof LearnerCommunitiesCreateIdCourseRouteRoute
  '/_learner/communities/$id/threads/$threadId': typeof LearnerCommunitiesIdThreadsThreadIdRoute
  '/_learner/communities/$id/articles/': typeof LearnerCommunitiesIdArticlesIndexRoute
  '/_learner/communities/$id/courses/': typeof LearnerCommunitiesIdCoursesIndexRoute
  '/_learner/communities/$id/threads/': typeof LearnerCommunitiesIdThreadsIndexRoute
  '/_learner/communities/create/$id/community/members': typeof LearnerCommunitiesCreateIdCommunityMembersRoute
  '/_learner/communities/create/$id/community/publish': typeof LearnerCommunitiesCreateIdCommunityPublishRoute
  '/_learner/communities/create/$id/community/settings': typeof LearnerCommunitiesCreateIdCommunitySettingsRoute
  '/_learner/communities/create/$id/community/': typeof LearnerCommunitiesCreateIdCommunityIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/test'
    | '/login'
    | '/calendar'
    | '/chat'
    | '/explore'
    | '/tasks'
    | '/x/dropdown'
    | '/x/editor-demo'
    | '/'
    | '/communities/$id'
    | '/communities'
    | '/communities/$id/'
    | '/communities/create'
    | '/communities/create/$id/community'
    | '/communities/create/$id/course'
    | '/communities/$id/threads/$threadId'
    | '/communities/$id/articles'
    | '/communities/$id/courses'
    | '/communities/$id/threads'
    | '/communities/create/$id/community/members'
    | '/communities/create/$id/community/publish'
    | '/communities/create/$id/community/settings'
    | '/communities/create/$id/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/test'
    | '/login'
    | '/calendar'
    | '/chat'
    | '/explore'
    | '/tasks'
    | '/x/dropdown'
    | '/x/editor-demo'
    | '/'
    | '/communities'
    | '/communities/$id'
    | '/communities/create'
    | '/communities/create/$id/course'
    | '/communities/$id/threads/$threadId'
    | '/communities/$id/articles'
    | '/communities/$id/courses'
    | '/communities/$id/threads'
    | '/communities/create/$id/community/members'
    | '/communities/create/$id/community/publish'
    | '/communities/create/$id/community/settings'
    | '/communities/create/$id/community'
  id:
    | '__root__'
    | '/_auth'
    | '/_learner'
    | '/test'
    | '/_auth/login'
    | '/_learner/calendar'
    | '/_learner/chat'
    | '/_learner/explore'
    | '/_learner/tasks'
    | '/x/dropdown'
    | '/x/editor-demo'
    | '/_learner/'
    | '/_learner/communities/$id'
    | '/_learner/communities/'
    | '/_learner/communities/$id/'
    | '/_learner/communities/create/'
    | '/_learner/communities/create/$id/community'
    | '/_learner/communities/create/$id/course'
    | '/_learner/communities/$id/threads/$threadId'
    | '/_learner/communities/$id/articles/'
    | '/_learner/communities/$id/courses/'
    | '/_learner/communities/$id/threads/'
    | '/_learner/communities/create/$id/community/members'
    | '/_learner/communities/create/$id/community/publish'
    | '/_learner/communities/create/$id/community/settings'
    | '/_learner/communities/create/$id/community/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LearnerRoute: typeof LearnerRouteWithChildren
  TestRoute: typeof TestRoute
  XDropdownRoute: typeof XDropdownRoute
  XEditorDemoRoute: typeof XEditorDemoRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LearnerRoute: LearnerRouteWithChildren,
  TestRoute: TestRoute,
  XDropdownRoute: XDropdownRoute,
  XEditorDemoRoute: XEditorDemoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_learner",
        "/test",
        "/x/dropdown",
        "/x/editor-demo"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login"
      ]
    },
    "/_learner": {
      "filePath": "_learner.tsx",
      "children": [
        "/_learner/calendar",
        "/_learner/chat",
        "/_learner/explore",
        "/_learner/tasks",
        "/_learner/",
        "/_learner/communities/$id",
        "/_learner/communities/",
        "/_learner/communities/create/",
        "/_learner/communities/create/$id/community",
        "/_learner/communities/create/$id/course"
      ]
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth.login.tsx",
      "parent": "/_auth"
    },
    "/_learner/calendar": {
      "filePath": "_learner/calendar.tsx",
      "parent": "/_learner"
    },
    "/_learner/chat": {
      "filePath": "_learner/chat.tsx",
      "parent": "/_learner"
    },
    "/_learner/explore": {
      "filePath": "_learner/explore.tsx",
      "parent": "/_learner"
    },
    "/_learner/tasks": {
      "filePath": "_learner/tasks.tsx",
      "parent": "/_learner"
    },
    "/x/dropdown": {
      "filePath": "x/dropdown.tsx"
    },
    "/x/editor-demo": {
      "filePath": "x/editor-demo.tsx"
    },
    "/_learner/": {
      "filePath": "_learner/index.tsx",
      "parent": "/_learner"
    },
    "/_learner/communities/$id": {
      "filePath": "_learner/communities/$id/route.tsx",
      "parent": "/_learner",
      "children": [
        "/_learner/communities/$id/",
        "/_learner/communities/$id/threads/$threadId",
        "/_learner/communities/$id/articles/",
        "/_learner/communities/$id/courses/",
        "/_learner/communities/$id/threads/"
      ]
    },
    "/_learner/communities/": {
      "filePath": "_learner/communities/index.tsx",
      "parent": "/_learner"
    },
    "/_learner/communities/$id/": {
      "filePath": "_learner/communities/$id/index.tsx",
      "parent": "/_learner/communities/$id"
    },
    "/_learner/communities/create/": {
      "filePath": "_learner/communities/create/index.tsx",
      "parent": "/_learner"
    },
    "/_learner/communities/create/$id/community": {
      "filePath": "_learner/communities/create/$id/community/route.tsx",
      "parent": "/_learner",
      "children": [
        "/_learner/communities/create/$id/community/members",
        "/_learner/communities/create/$id/community/publish",
        "/_learner/communities/create/$id/community/settings",
        "/_learner/communities/create/$id/community/"
      ]
    },
    "/_learner/communities/create/$id/course": {
      "filePath": "_learner/communities/create/$id/course/route.tsx",
      "parent": "/_learner"
    },
    "/_learner/communities/$id/threads/$threadId": {
      "filePath": "_learner/communities/$id/threads.$threadId.tsx",
      "parent": "/_learner/communities/$id"
    },
    "/_learner/communities/$id/articles/": {
      "filePath": "_learner/communities/$id/articles.index.tsx",
      "parent": "/_learner/communities/$id"
    },
    "/_learner/communities/$id/courses/": {
      "filePath": "_learner/communities/$id/courses.index.tsx",
      "parent": "/_learner/communities/$id"
    },
    "/_learner/communities/$id/threads/": {
      "filePath": "_learner/communities/$id/threads.index.tsx",
      "parent": "/_learner/communities/$id"
    },
    "/_learner/communities/create/$id/community/members": {
      "filePath": "_learner/communities/create/$id/community/members.tsx",
      "parent": "/_learner/communities/create/$id/community"
    },
    "/_learner/communities/create/$id/community/publish": {
      "filePath": "_learner/communities/create/$id/community/publish.tsx",
      "parent": "/_learner/communities/create/$id/community"
    },
    "/_learner/communities/create/$id/community/settings": {
      "filePath": "_learner/communities/create/$id/community/settings.tsx",
      "parent": "/_learner/communities/create/$id/community"
    },
    "/_learner/communities/create/$id/community/": {
      "filePath": "_learner/communities/create/$id/community/index.tsx",
      "parent": "/_learner/communities/create/$id/community"
    }
  }
}
ROUTE_MANIFEST_END */
