/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as learnerIndexImport } from './routes/(learner)/index'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as learnerEnrolmentsUidImport } from './routes/(learner)/enrolments.$uid'

// Create/Update Routes

const learnerIndexRoute = learnerIndexImport.update({
  id: '/(learner)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const learnerEnrolmentsUidRoute = learnerEnrolmentsUidImport.update({
  id: '/(learner)/enrolments/$uid',
  path: '/enrolments/$uid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(learner)/': {
      id: '/(learner)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof learnerIndexImport
      parentRoute: typeof rootRoute
    }
    '/(learner)/enrolments/$uid': {
      id: '/(learner)/enrolments/$uid'
      path: '/enrolments/$uid'
      fullPath: '/enrolments/$uid'
      preLoaderRoute: typeof learnerEnrolmentsUidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/': typeof learnerIndexRoute
  '/enrolments/$uid': typeof learnerEnrolmentsUidRoute
}

export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof learnerIndexRoute
  '/enrolments/$uid': typeof learnerEnrolmentsUidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)/login': typeof authLoginRoute
  '/(learner)/': typeof learnerIndexRoute
  '/(learner)/enrolments/$uid': typeof learnerEnrolmentsUidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/enrolments/$uid'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/enrolments/$uid'
  id:
    | '__root__'
    | '/(auth)/login'
    | '/(learner)/'
    | '/(learner)/enrolments/$uid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authLoginRoute: typeof authLoginRoute
  learnerIndexRoute: typeof learnerIndexRoute
  learnerEnrolmentsUidRoute: typeof learnerEnrolmentsUidRoute
}

const rootRouteChildren: RootRouteChildren = {
  authLoginRoute: authLoginRoute,
  learnerIndexRoute: learnerIndexRoute,
  learnerEnrolmentsUidRoute: learnerEnrolmentsUidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)/login",
        "/(learner)/",
        "/(learner)/enrolments/$uid"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(learner)/": {
      "filePath": "(learner)/index.tsx"
    },
    "/(learner)/enrolments/$uid": {
      "filePath": "(learner)/enrolments.$uid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
